### ISSUE TITLE
Memory leak when `transaction.complete()` is not awaited

### ISSUE THREAD

**Issue by byzyk** [powersync-ja/powersync-js#247] opened 2024-07-25 20:19 UTC
Failure to call `await transaction.complete()` inside `uploadData()` results in an endless loop and eventually hangs the browser.

I understand that it's not intended behavior, so I would appreciate it if we could find a way to detect the memory leak and throw an exception instead. It would potentially save many dev hours for those who'll make the same mistake as I just did 😃

PS. Amazing library, I enjoy it quite a lot the past few days!

**Comment by stevensJourney** [comment] 2024-07-26 13:35
Thanks for logging this issue. We'll investigate by reproducing on our side.

**Comment by stevensJourney** [comment] 2024-08-01 07:26
Hi @byzyk, I tried to reproduce a leak and browser hang on my side by removing [this](https://github.com/powersync-ja/powersync-js/blob/8fe44fbe7a880350afd4bd7518fe5845e83cb98d/demos/react-supabase-todolist/src/library/powersync/SupabaseConnector.ts#L141) line in our demo.

I did notice that the upload function remains in a _non-blocking_ loop, but I didn't notice indefinite increasing memory usage or a hang. Attached below is the profile of memory usage which did remain stable.
![image](https://github.com/user-attachments/assets/824347c3-a57d-4c54-ab66-9370545cd1ce)

We are still investigating ways to potentially detect if the transaction is not completed and avoid the loop. It would be helpful if you could share some more context on how the hang or leak occurred on your side.

**Comment by stevensJourney** [comment] 2024-08-07 15:59
We've added some additional checks in these versions https://github.com/powersync-ja/powersync-js/pull/255 to delay infinite loops if no uploads are performed in the `uploadData` method of the `BackendConnector`. This should help a lot with these kinds of issues. Generally an infinite loop could cause large memory spikes depending on what the client code is doing in `uploadData`. I'm going to close this for now since I could not reproduce a memory leak on my side.

**Closed by stevensJourney** 2024-08-07 15:59 UTC

**Comment by byzyk** [comment] 2024-08-21 18:14
hi @stevensJourney, thanks for the update.

I just wanted to clarify from my side - you are correct, what was happening here was an infinite loop. In my case, I had a memory leak probably due to some additional logic inside `uploadData`. Thanks for patching this!
